name = "paddlepal"
main = "src/index.ts"
compatibility_date = "2026-02-17"

[[d1_databases]]
binding = "DB"
database_name = "paddlepal-d1"
database_id = "e495c6a1-a0a5-45c8-ac0b-1ab6ba7cf6b3"

[[r2_buckets]]
bucket_name = "paddlepal-r2"
binding = "FILES"

[[kv_namespaces]]
binding = "SESSIONS"
id = "736076b3f04e4cd89cbcb86e541c855e"

[[durable_objects.bindings]]
name = "PADDLEPAL_DO"
class_name = "LiveDO"

[[migrations]]
tag = "v1"
new_classes = ["LiveDO"]

[vars]
ADMIN_USER = "admin"
ADMIN_PASS = "paddlepal2026"
